@startuml Aktivitätsdiagramm Login

title Aktivitätsdiagramm - Login

start

:LoginPage öffnen;
:Username und Passwort eingeben;
:Button "Anmelden" klicken;

if (Felder ausgefüllt?) then ([nein])
  :Validierungsfehler anzeigen;
  stop
else ([ja])
  :REST Request an Keycloak Token-Endpoint;
  note right
    POST /realms/{realm}/protocol/openid-connect/token
    grant_type=password
    client_id, username, password
  end note
  
  if (Credentials korrekt?) then ([ja])
    :Access-Token und Refresh-Token erhalten;
    :Tokens in localStorage speichern;
    :User-Daten aus JWT extrahieren;
    :Weiterleitung zur Startseite;
    
    if (User ist Admin?) then ([ja])
      :Link "Buch erstellen" anzeigen;
    else ([nein])
      :Standardansicht;
    endif
    
  else ([nein])
    :Fehlermeldung: Ungültige Anmeldedaten;
  endif
endif

stop

@enduml
